productsapp/urls.py
from django.urls import path

from . import views 
from .views import ProductView

app_name = 'productsapp'
urlpatterns = [
    #path('', views.home, name='home'),
    # path('', views.list_product, name='product'),
    path('', ProductView.as_view(), name='product'),
    path('product/add', views.add_product, name='add-product'),
    path('product/edit/<int:product_id>/', views.edit_product, name='edit-product'),
    path('category/', views.category, name='category'),
    path('category/add', views.add_category, name='add-category'),
    path('product-type/', views.product_type, name='product-type'),
    path('product-type/add', views.add_product_type, name='add-product-type'),
    path('ajax/', ProductView.as_view(), name='ajax'),

]

productsproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productsapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productsapp/models.py
from django.db import models

# Create your models here.
class ProductType(models.Model):
    name = models.CharField(max_length=30, verbose_name='Тип продукта')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип продукта'
        verbose_name_plural = 'Типы продуктов'
        

class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='Категория')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Product(models.Model):
    product_type = models.ForeignKey(ProductType, on_delete=models.PROTECT, verbose_name='Тип продукта') 
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name = 'Категория') 
    name = models.CharField(max_length=30, verbose_name='Продукт')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField('Фото', upload_to='productsapp_images/', blank=False)

    def __str__(self):
        return self.name   

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты' 
    
    

productsapp/forms.py
from django import forms
from productsapp.models import Product, Category, ProductType

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ProductTypeForm(forms.ModelForm):
    class Meta:
        model = ProductType
        fields = '__all__'

productsapp/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from productsapp.models import Product, Category, ProductType

from productsapp.forms import ProductForm, CategoryForm, ProductTypeForm 

from django.views.generic import View
from django.http import JsonResponse
import json

# Create your views here.
"""
def home(request):
    # products = Product.objects.all()
    # return render(request, 'productsapp/product.html', {'products': products})
    return redirect(product)
"""
def list_product(request):
    products = Product.objects.all()
    return render(request, 'productsapp/product.html', {'products': products})

def add_product(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('productsapp:product')
    return render(request, 'productsapp/add_product.html', {'form': form})

def edit_product(request, product_id):
    #form = ProductForm(instance = Product.objects.get(id = product_id))
    form = ProductForm(instance = get_object_or_404(Product, pk=product_id))
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance = Product.objects.get(id = product_id))
        if form.is_valid():
            form.save()
            return redirect('productsapp:product')
    return render(request, 'productsapp/edit_product.html', {'form': form})

def category(request):
    categories = Category.objects.all()
    return render(request, 'productsapp/category.html', {'categories': categories})

def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('productsapp:category')
    return render(request, 'productsapp/add_category.html', {'form': form})

def product_type(request):
    types = ProductType.objects.all()
    return render(request, 'productsapp/product_type.html', {'types': types})

def add_product_type(request):
    form = ProductTypeForm()
    if request.method == 'POST':
        form = ProductTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('productsapp:product-type')
    return render(request, 'productsapp/add_product_type.html', {'form': form})

class ProductView(View):

    def get(self, request):
        products = Product.objects.all()
        return render(request, 'productsapp/product.html', {'products': products})

    def post(self, request):
        if request.is_ajax():
            data = json.loads(request.body.decode("utf-8"))
            query = data.get('query')
        
            products = Product.objects.filter(name__icontains=query)
            
            return render(request, 'productsapp/ajax.html', {'products': products})
        else:
            JsonResponse({'msg': 'This is no ajax request'}, status=400)

productsapp/templates/productsapp/add_category.html
{% extends 'productsapp/base.html' %}
{% load bootstrap3 %}

{% block meta_title %}Add Category{% endblock meta_title %}

{% block heading %}Добавление категории{% endblock heading %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-danger pull-right">Добавить</button>

{% endblock content %}

productsapp/templates/productsapp/add_product.html
{% extends 'productsapp/base.html' %}
{% load bootstrap3 %}

{% block meta_title %}Add Product{% endblock meta_title %}

{% block heading %}Добавление продукта{% endblock heading %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-danger pull-right">Добавить</button>

    <br>

{% endblock content %}

productsapp/templates/productsapp/add_product_type.html
{% extends 'productsapp/base.html' %}
{% load bootstrap3 %}

{% block meta_title %}Add Product Type{% endblock meta_title %}

{% block heading %}Добавление типа продукта{% endblock heading %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-danger pull-right">Добавить</button>

{% endblock content %}

productsapp/templates/productsapp/ajax.html
<table class="table table-bordered">
        <tr>
            <th>Фото</th>
            <th>Наименование</th> 
            <th>Категория </th>
            <th>Тип продукта </th>
            <th>Описание </th>
            <th>Редактирование </th>
        </tr>


        {% for product in products%}

        <tr>
            <td>
                {% if product.image %}
                    <img class="img-thumbnail"  src="{{ product.image.url }} " alt="" width="150" height="150">
                {% else %}
                    <img class="img-thumbnail"  src="/static/productsapp/img/default_image.jpg" alt="" width="150" height="150">
                {% endif %}
            </td>
            <td>{{ product.name }}</td> 
            <td>{{product.category}}</td>
            <td>{{product.product_type}}</td>
            <td>{{product.description}}</td>
            <td><a class="btn btn-default" href="{% url 'productsapp:edit-product' product.id %}">Редактировать</a></td>
        </tr>


        {% endfor %}

    </table>

productsapp/templates/productsapp/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">

    <title>{% block meta_title %}{% endblock meta_title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ PORTAL_URL}}{% static "productsapp/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ PORTAL_URL}}{% static "productsapp/css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ PORTAL_URL}}{% static "productsapp/css/sticky-footer-navbar.css" %}" rel="stylesheet">    

    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'productsapp:product' %}">Test task</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li {% if request.path == '/' or '/product' in request.path %}class="active"{% endif %}> <a href="{% url 'productsapp:product' %}">Продукты</a> </li>
            <li {% if '/category' in request.path %}class="active"{% endif %}> <a href="{% url 'productsapp:category' %}">Категории</a> </li>
            <li {% if '/product-type' in request.path %}class="active"{% endif %}> <a href="{% url 'productsapp:product-type' %}">Типы продуктов</a> </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->
    <div class="container">
        <div class="page-header">
            <h1>
                {% block heading %}{% endblock %}
                {% block button %}{% endblock button %} 
            </h1>
        </div>
 
        {% block content %}{% endblock content %}    
    </div>

    <footer class="footer navbar-inverse">
      <div class="container">
        <p class="text-muted">&copy; Test task 2018</p>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{{ PORTAL_URL}}{% static "js/bootstrap.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ PORTAL_URL}}{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

productsapp/templates/productsapp/category.html
{% extends 'productsapp/base.html' %}

{% block meta_title  %}Category{% endblock meta_title %}

{% block heading %}Категории{% endblock heading%}

{% block button %} 
  <a href="{% url 'productsapp:add-category' %}" class="btn btn-danger btn-sm" role="button">Добавить</a>
{% endblock button %}

{% block content %}

<table class="table table-bordered">
  <tr>
    <th>ID</th>
    <th>Название категории</th>
  </tr>

    {% for category in categories%}

  <tr>
    <td>{{category.id}}</td>
    <td>{{category.name}}</td>
  </tr>


    {% endfor %}

</table>

{% endblock content %}

productsapp/templates/productsapp/edit_product.html
{% extends 'productsapp/base.html' %}
{% load bootstrap3 %}

{% block meta_title %}Edit Product{% endblock  %}

{% block heading %}Редактирование продукта{% endblock heading %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-danger pull-right">Применить</button>

{% endblock content %}

productsapp/templates/productsapp/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title> 
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

    <script src="{% static 'js/bootstrap.min.js'%}"></script>
</head>
<body>
    <h1>Hello Python</h1>

    {% for product in products%}
        <div>
            <h2>{{product.name}}</h2>
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                {% endif %}
            <div>{{product.category}}</div>
            <div>{{product.product_type}}</div>
            <div>{{product.description}}</div>
        </div>
    {% endfor %}
</body>
</html>

productsapp/templates/productsapp/product.html
{% extends 'productsapp/base.html' %}

{% block meta_title %}Products{% endblock meta_title %}

{% block heading %}Продукты{% endblock heading %}

{% block button %} 
    <a href="{% url 'productsapp:add-product' %}" class="btn btn-danger btn-sm" role="button">Добавить</a>
{% endblock button %}

{% block content %}

{% csrf_token %}

<div class="row">
  <div class="col-lg-3">
  </div><!-- /.col-lg-6 -->
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control search" placeholder="Search for..." name="inpQuery">
      <span class="input-group-btn">
        <button class="btn btn-default search" type="button">Go!</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

<br>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"></div>

    <table class="table table-bordered">
        <tr>
            <th>Фото</th>
            <th>Наименование</th> 
            <th>Категория </th>
            <th>Тип продукта </th>
            <th>Описание </th>
            <th>Редактирование </th>
        </tr>


        {% for product in products%}

        <tr>
            <td>
                {% if product.image %}
                    <img class="img-thumbnail"  src="{{ product.image.url }} " alt="" width="150" height="150">
                {% else %}
                    <img class="img-thumbnail"  src="/static/productsapp/img/default_image.jpg" alt="" width="150" height="150">
                {% endif %}
            </td>
            <td>{{ product.name }}</td> 
            <td>{{product.category}}</td>
            <td>{{product.product_type}}</td>
            <td>{{product.description}}</td>
            <td><a class="btn btn-default" href="{% url 'productsapp:edit-product' product.id %}">Редактировать</a></td>
        </tr>


        {% endfor %}

    </table>
</div>

{% endblock content %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function(){
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", $('input[name="csrfmiddlewaretoken"]').val());
            }
        }
    });

    $('button.search').on('click',function(){
        var $inp_query = $('input[name="inpQuery"]');

     //   if ($inp_query.val()){
            $.ajax({
                type: "POST",
                url: "/",
                data: JSON.stringify({'query': $inp_query.val()}),
                contentType: "application/json",
                cache: false,
                success: function(data){
                    $(".table").replaceWith(data);
                    console.log(data);
                },
                error: function(xhr){
                    console.log(xhr);
                }
            });
       // }
    });
});
</script> 

{% endblock extra_js %}

productsapp/templates/productsapp/product_type.html
{% extends 'productsapp/base.html' %}

{% block meta_title %}Category{% endblock meta_title%}

{% block heading %}Типы продуктов{% endblock heading %}

{% block button %} 
  <a href="{% url 'productsapp:add-product-type' %}" class="btn btn-danger btn-sm" role="button">Добавить</a>
{% endblock button %}

{% block content  %}

<table class="table table-bordered">
  <tr>
    <th>ID</th>
    <th>Название категории</th>
  </tr>

    {% for type in types %}

      <tr>
        <td>{{type.id}}</td>
        <td>{{type.name}}</td>
      </tr>

    {% endfor %}

</table>

{% endblock content %}